quiet: false
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDirRelative}}/mocks"
mockname: "{{.InterfaceName|camelcase}}"
outpkg: "mocks"

packages:
  github.com/danielMensah/go-ddb/internal/database:
    interfaces:
      DynamoDBClient:
  github.com/danielMensah/go-ddb:
    interfaces:
      Client: